=== PHANTOM-Platform/OfflineMOM/models/component_network.xsd
<xs:schema xmlns="CN"  targetNamespace="CN" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="nf-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="execution-time"/>
	<xs:enumeration value="energy-consumption"/>
  </xs:restriction>
</xs:simpleType>
  

  <xs:element name="non-functional">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name" use="required"/>
          <xs:attribute type="nf-type" name="type" use="required"/>
          <xs:attribute type="xs:short" name="max-value" use="required"/>
          <xs:attribute type="xs:string" name="measurement-unit" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
<xs:simpleType name="monitoring-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="execution-time"/>
	<xs:enumeration value="energy-consumption"/>
  </xs:restriction>
</xs:simpleType>
  
  <xs:element name="monitoring">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name" use="required"/>
          <xs:attribute type="monitoring-type" name="type" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="PT-parallelisation-directive">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="set-by" use="required"/>
          <xs:attribute type="xs:string" name="name" use="required"/>
          <xs:attribute type="xs:byte" name="max_number" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="MBT-estimated-computation-time">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:short" name="value" use="required"/>
          <xs:attribute type="xs:string" name="measurement-unit" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="MF-monitored-computation-time">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="measurement-unit" use="required"/>
          <xs:attribute type="xs:short" name="value" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="requirements">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="non-functional" minOccurs="0"/>
        <xs:element ref="monitoring" minOccurs="0"/>
        <xs:element ref="data-integrity" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="set-by" use="required"/>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="target" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="header">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="lang" use="required"/>
          <xs:attribute type="xs:string" name="path" use="required"/>
          <xs:attribute type="xs:string" name="file" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="source">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="lang" use="optional"/>
          <xs:attribute type="xs:string" name="path" use="optional"/>
          <xs:attribute type="xs:string" name="file" use="optional"/>
          <xs:attribute type="xs:string" name="name" use="optional"/>
          <xs:attribute type="xs:string" name="port-name" use="optional"/>
          <xs:attribute type="xs:string" name="type" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="port">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name" use="required"/>
          <xs:attribute type="xs:string" name="type" use="required"/>
          <xs:attribute type="xs:string" name="peer-object" use="required"/>
          <xs:attribute type="xs:string" name="peer-name" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="data-integrity">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="value" use="required"/>
          <xs:attribute type="xs:string" name="measurement-unit" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="PT-access-number">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:byte" name="value" use="required"/>
          <xs:attribute type="xs:string" name="set-by" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="target">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name" use="required"/>
          <xs:attribute type="xs:string" name="port-name" use="required"/>
          <xs:attribute type="xs:string" name="type" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
<xs:simpleType name="comp-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="synchronous"/>
	<xs:enumeration value="asynchronous"/>
	<xs:enumeration value="OTHER-TBD"/>
  </xs:restriction>
</xs:simpleType>
    
  <xs:element name="component">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PT-parallelisation-directive"/>
        <xs:element ref="MBT-estimated-computation-time"/>
        <xs:element ref="MF-monitored-computation-time"/>
        <xs:element ref="requirements" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="header" maxOccurs="unbounded" minOccurs="1"/>
        <xs:element ref="source" maxOccurs="1" minOccurs="1"/>
        <xs:element ref="port" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="comp-type" name="type" use="required"/>
    </xs:complexType>
  </xs:element>

<xs:simpleType name="comm-type">
  <xs:restriction base="xs:string">
	<xs:enumeration value="Queue"/>
	<xs:enumeration value="Signal"/>
	<xs:enumeration value="Shared-Memory"/>
  </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="ob-type">
  <xs:restriction base="xs:string">
	<xs:enumeration value="FIFO"/>
	<xs:enumeration value="OTHER-TBD"/>
  </xs:restriction>
</xs:simpleType>

  <xs:element name="comm-object">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="requirements"/>
        <xs:element ref="PT-access-number"/>
        <xs:element ref="source" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="target" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="comm-type" name="type" use="required"/>
      <xs:attribute type="ob-type" name="object-class" use="required"/>
      <xs:attribute type="xs:byte" name="size" use="required"/>
      <xs:attribute type="xs:byte" name="item-size" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="application">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="requirements"/>
        <xs:element ref="component" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="comm-object" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:string" name="value"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== PHANTOM-Platform/OfflineMOM/examples/simple-dualcore/cn.xml
<application xmlns="CN" name="Example Application" xsi:schemaLocation="../models/component_network.xsd">

<component name="ComponentA" type="asynchronous">
    <MBT-estimated-computation-time value="60" measurement-unit="ns"/>
    <MF-monitored-computation-time measurement-unit="ns" value="400"/>

    <requirements set-by="USER" name="componentA_requirements" target="ComponentA">
		<non-functional name="Simons_WCET" type="execution-time" max-value="500" measurement-unit="ns"/>
	</requirements>

</component>


<component name="ComponentB" type="asynchronous">
    <MBT-estimated-computation-time value="80" measurement-unit="ns"/>
    <MF-monitored-computation-time measurement-unit="ns" value="400"/>

    <requirements set-by="USER" name="componentA_requirements" target="ComponentB">
		<non-functional name="Simons_WCET" type="execution-time" max-value="500" measurement-unit="ns"/>
	</requirements>

</component>

<component name="ComponentC" type="asynchronous">A
    <MBT-estimated-computation-time value="90" measurement-unit="ns"/>
    <MF-monitored-computation-time measurement-unit="ns" value="400"/>

    <requirements set-by="USER" name="componentA_requirements" target="ComponentC">
		<non-functional name="Simons_WCET" type="execution-time" max-value="500" measurement-unit="ns"/>
	</requirements>

</component>

</application>
